### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by solap** [lmcalpin/turntable-api-rb#2]
I'm getting this error when I run the lastfm_info_bot.
lastfm_info_bot.rb:12:in `<main>': undefined method`[]' for nil:NilClass (NoMethodError)

friendly_bot doesn't get the same error.

This line is failing:
last_fm_api_key = yaml['lastfm']['key'] 

Neither lastfm nor key is in the bot.yml config file.

Any ideas?

Can't wait to get this working!

**Comment by lmcalpin** [comment]
You have to acquire those keys yourself.  You can get a Last.FM developer key here: http://www.last.fm/api, and you can use this bookmarklet to find your turntable auth/userid keys while logged on to Turntable here: http://alaingilbert.github.com/Turntable-API/bookmarklet.html.

You might also look into this newer turntable library (https://github.com/obrie/turntabler) since I haven't worked on this for quite some time.
